# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'last_last.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import resources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Christmas_card_maker(object):
    def setupUi(self, Christmas_card_maker):
        Christmas_card_maker.setObjectName("Christmas_card_maker")
        Christmas_card_maker.resize(821, 575)
        Christmas_card_maker.setMouseTracking(False)
        Christmas_card_maker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(Christmas_card_maker)
        self.centralwidget.setObjectName("centralwidget")
        self.useless = QtWidgets.QLabel(self.centralwidget)
        self.useless.setGeometry(QtCore.QRect(10, 0, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.useless.setFont(font)
        self.useless.setObjectName("useless")
        self.useless_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.useless_label_3.setGeometry(QtCore.QRect(250, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.useless_label_3.setFont(font)
        self.useless_label_3.setObjectName("useless_label_3")
        self.useless_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.useless_label_2.setGeometry(QtCore.QRect(250, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.useless_label_2.setFont(font)
        self.useless_label_2.setObjectName("useless_label_2")
        self.first_pattern = QtWidgets.QRadioButton(self.centralwidget)
        self.first_pattern.setEnabled(True)
        self.first_pattern.setGeometry(QtCore.QRect(120, 460, 31, 31))
        self.first_pattern.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.first_pattern.setCheckable(True)
        self.first_pattern.setChecked(True)
        self.first_pattern.setObjectName("first_pattern")
        self.second_pattern = QtWidgets.QRadioButton(self.centralwidget)
        self.second_pattern.setGeometry(QtCore.QRect(400, 460, 31, 31))
        self.second_pattern.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.second_pattern.setObjectName("second_pattern")
        self.third_pattern = QtWidgets.QRadioButton(self.centralwidget)
        self.third_pattern.setGeometry(QtCore.QRect(680, 460, 31, 31))
        self.third_pattern.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.third_pattern.setObjectName("third_pattern")
        self.useless_3 = QtWidgets.QLabel(self.centralwidget)
        self.useless_3.setGeometry(QtCore.QRect(490, 150, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.useless_3.setFont(font)
        self.useless_3.setObjectName("useless_3")
        self.useless_label = QtWidgets.QLabel(self.centralwidget)
        self.useless_label.setGeometry(QtCore.QRect(440, 190, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.useless_label.setFont(font)
        self.useless_label.setObjectName("useless_label")
        self.useless_2 = QtWidgets.QLabel(self.centralwidget)
        self.useless_2.setGeometry(QtCore.QRect(0, 520, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.useless_2.setFont(font)
        self.useless_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.useless_2.setObjectName("useless_2")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(630, 490, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.start_btn.setFont(font)
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setObjectName("start_btn")
        self.text_sender = QtWidgets.QTextEdit(self.centralwidget)
        self.text_sender.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.text_sender.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_sender.setObjectName("text_sender")
        self.text_recipient = QtWidgets.QTextEdit(self.centralwidget)
        self.text_recipient.setGeometry(QtCore.QRect(10, 100, 211, 31))
        self.text_recipient.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_recipient.setObjectName("text_recipient")
        self.greeting_text = QtWidgets.QTextEdit(self.centralwidget)
        self.greeting_text.setGeometry(QtCore.QRect(10, 140, 371, 131))
        self.greeting_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.greeting_text.setPlaceholderText("")
        self.greeting_text.setObjectName("greeting_text")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setEnabled(False)
        self.error.setGeometry(QtCore.QRect(460, 240, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.error.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setMouseTracking(False)
        self.error.setObjectName("error")
        self.error_length = QtWidgets.QLabel(self.centralwidget)
        self.error_length.setEnabled(False)
        self.error_length.setGeometry(QtCore.QRect(10, 270, 371, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.error_length.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error_length.setFont(font)
        self.error_length.setMouseTracking(False)
        self.error_length.setObjectName("error_length")
        self.success = QtWidgets.QLabel(self.centralwidget)
        self.success.setEnabled(False)
        self.success.setGeometry(QtCore.QRect(740, 0, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.success.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.success.setFont(font)
        self.success.setMouseTracking(False)
        self.success.setObjectName("success")
        self.x_sender = QtWidgets.QSpinBox(self.centralwidget)
        self.x_sender.setGeometry(QtCore.QRect(590, 80, 42, 22))
        self.x_sender.setMinimum(-1)
        self.x_sender.setMaximum(99999)
        self.x_sender.setProperty("value", -1)
        self.x_sender.setObjectName("x_sender")
        self.useless_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.useless_15.setGeometry(QtCore.QRect(0, 300, 261, 161))
        self.useless_15.setObjectName("useless_15")
        self.useless_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.useless_7.setGeometry(QtCore.QRect(280, 290, 261, 171))
        self.useless_7.setObjectName("useless_7")
        self.useless_14 = QtWidgets.QTextBrowser(self.centralwidget)
        self.useless_14.setGeometry(QtCore.QRect(560, 290, 261, 171))
        self.useless_14.setObjectName("useless_14")
        self.useless_8 = QtWidgets.QLabel(self.centralwidget)
        self.useless_8.setGeometry(QtCore.QRect(780, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_8.setFont(font)
        self.useless_8.setObjectName("useless_8")
        self.useless_9 = QtWidgets.QLabel(self.centralwidget)
        self.useless_9.setGeometry(QtCore.QRect(690, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_9.setFont(font)
        self.useless_9.setObjectName("useless_9")
        self.useless_10 = QtWidgets.QLabel(self.centralwidget)
        self.useless_10.setGeometry(QtCore.QRect(600, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_10.setFont(font)
        self.useless_10.setObjectName("useless_10")
        self.useless_11 = QtWidgets.QLabel(self.centralwidget)
        self.useless_11.setGeometry(QtCore.QRect(600, 120, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_11.setFont(font)
        self.useless_11.setObjectName("useless_11")
        self.useless_12 = QtWidgets.QLabel(self.centralwidget)
        self.useless_12.setGeometry(QtCore.QRect(690, 120, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_12.setFont(font)
        self.useless_12.setObjectName("useless_12")
        self.useless_13 = QtWidgets.QLabel(self.centralwidget)
        self.useless_13.setGeometry(QtCore.QRect(780, 120, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.useless_13.setFont(font)
        self.useless_13.setObjectName("useless_13")
        self.x_recipient = QtWidgets.QSpinBox(self.centralwidget)
        self.x_recipient.setGeometry(QtCore.QRect(680, 80, 42, 22))
        self.x_recipient.setMinimum(-1)
        self.x_recipient.setMaximum(99999)
        self.x_recipient.setProperty("value", -1)
        self.x_recipient.setObjectName("x_recipient")
        self.x_greeting = QtWidgets.QSpinBox(self.centralwidget)
        self.x_greeting.setGeometry(QtCore.QRect(770, 80, 42, 22))
        self.x_greeting.setMinimum(-1)
        self.x_greeting.setMaximum(99999)
        self.x_greeting.setProperty("value", -1)
        self.x_greeting.setObjectName("x_greeting")
        self.y_recipient = QtWidgets.QSpinBox(self.centralwidget)
        self.y_recipient.setGeometry(QtCore.QRect(680, 150, 42, 22))
        self.y_recipient.setMinimum(-1)
        self.y_recipient.setMaximum(99999)
        self.y_recipient.setProperty("value", -1)
        self.y_recipient.setObjectName("y_recipient")
        self.y_sender = QtWidgets.QSpinBox(self.centralwidget)
        self.y_sender.setGeometry(QtCore.QRect(590, 150, 42, 22))
        self.y_sender.setMinimum(-1)
        self.y_sender.setMaximum(99999)
        self.y_sender.setProperty("value", -1)
        self.y_sender.setObjectName("y_sender")
        self.y_greeting = QtWidgets.QSpinBox(self.centralwidget)
        self.y_greeting.setGeometry(QtCore.QRect(770, 150, 42, 22))
        self.y_greeting.setMinimum(-1)
        self.y_greeting.setMaximum(99999)
        self.y_greeting.setProperty("value", -1)
        self.y_greeting.setObjectName("y_greeting")
        self.useless_4 = QtWidgets.QLabel(self.centralwidget)
        self.useless_4.setGeometry(QtCore.QRect(590, 30, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.useless_4.setFont(font)
        self.useless_4.setObjectName("useless_4")
        self.useless_5 = QtWidgets.QLabel(self.centralwidget)
        self.useless_5.setGeometry(QtCore.QRect(680, 30, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.useless_5.setFont(font)
        self.useless_5.setObjectName("useless_5")
        self.useless_6 = QtWidgets.QLabel(self.centralwidget)
        self.useless_6.setGeometry(QtCore.QRect(770, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.useless_6.setFont(font)
        self.useless_6.setObjectName("useless_6")
        Christmas_card_maker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Christmas_card_maker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 21))
        self.menubar.setObjectName("menubar")
        Christmas_card_maker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Christmas_card_maker)
        self.statusbar.setObjectName("statusbar")
        Christmas_card_maker.setStatusBar(self.statusbar)

        self.retranslateUi(Christmas_card_maker)
        QtCore.QMetaObject.connectSlotsByName(Christmas_card_maker)


    def retranslateUi(self, Christmas_card_maker):
        _translate = QtCore.QCoreApplication.translate
        Christmas_card_maker.setWindowTitle(_translate("Christmas_card_maker", "Christmas card maker"))
        self.useless.setText(_translate("Christmas_card_maker", "Введите данные:"))
        self.useless_label_3.setText(_translate("Christmas_card_maker", "- отправитель"))
        self.useless_label_2.setText(_translate("Christmas_card_maker", "- адресат"))
        self.first_pattern.setText(_translate("Christmas_card_maker", "1"))
        self.second_pattern.setText(_translate("Christmas_card_maker", "2"))
        self.third_pattern.setText(_translate("Christmas_card_maker", "3"))
        self.useless_3.setText(_translate("Christmas_card_maker", "текст "))
        self.useless_label.setText(_translate("Christmas_card_maker", "поздравления *"))
        self.useless_2.setText(_translate("Christmas_card_maker", "* звездочкой помеченны поля, обязательные к заполнению"))
        self.start_btn.setText(_translate("Christmas_card_maker", "СГЕНЕРИРОВАТЬ!"))
        self.greeting_text.setHtml(_translate("Christmas_card_maker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.error.setText(_translate("Christmas_card_maker", "Введите текст!!!"))
        self.error_length.setText(_translate("Christmas_card_maker", "Превышен лимит символов."))
        self.success.setText(_translate("Christmas_card_maker", "sucsessfully"))
        self.useless_15.setHtml(_translate("Christmas_card_maker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/pat_1.jpg\" /></p></body></html>"))
        self.useless_7.setHtml(_translate("Christmas_card_maker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/pat_2.jpg\" /></p></body></html>"))
        self.useless_14.setHtml(_translate("Christmas_card_maker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/pat_3.jpg\" /></p></body></html>"))
        self.useless_8.setText(_translate("Christmas_card_maker", "x"))
        self.useless_9.setText(_translate("Christmas_card_maker", "x"))
        self.useless_10.setText(_translate("Christmas_card_maker", "x"))
        self.useless_11.setText(_translate("Christmas_card_maker", "y"))
        self.useless_12.setText(_translate("Christmas_card_maker", "y"))
        self.useless_13.setText(_translate("Christmas_card_maker", "y"))
        self.useless_4.setText(_translate("Christmas_card_maker", "sender"))
        self.useless_5.setText(_translate("Christmas_card_maker", "recipient"))
        self.useless_6.setText(_translate("Christmas_card_maker", "greeting"))


